# Generated by Django 3.1.1 on 2020-09-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=12)),
                ('physical_address', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=90)),
                ('job_title', models.CharField(max_length=500)),
                ('job_description', models.CharField(max_length=4000)),
                ('status', models.BooleanField(default=False)),
                ('date_needed', models.DateField()),
                ('attachments_file_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=12)),
                ('email_address', models.CharField(max_length=45)),
                ('physical_address', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('date_applied', models.DateField()),
                ('attachments_file_name', models.CharField(max_length=45)),
            ],
        ),
    ]
