# Generated by Django 3.1.1 on 2020-10-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
