# Generated by Django 3.1.2 on 2020-10-15 22:50

from django.db import migrations, models
import employment_agent.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('employment_agent', '0005_auto_20201015_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='attachments_file_name',
        ),
        migrations.AddField(
            model_name='employer',
            name='resume',
            field=models.FileField(default='employer_files/Resume.docx', upload_to=employment_agent.helpers.RandomFileName('employer_files')),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='resume',
            field=models.FileField(default='job_seeker_files/Resume.docx', upload_to=employment_agent.helpers.RandomFileName('job_seeker_files')),
        ),
    ]
