# Generated by Django 3.1.2 on 2020-10-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_agent', '0006_auto_20201015_2250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.AlterField(
            model_name='employer',
            name='email_address',
            field=models.EmailField(max_length=90),
        ),
    ]
