# Generated by Django 3.1.2 on 2020-10-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_agent', '0008_auto_20201030_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='description',
            field=models.CharField(default='Lorem ipsum dolor, ndokungoisa any text kuti zviende mberi', max_length=4000),
            preserve_default=False,
        ),
    ]
